import card from "./productPics/card.JPG"
import cat from "./productPics/cat.JPG"
import jugs from "./productPics/jugs.JPG"
import makeupBrush from "./productPics/makeupBrush.JPG"
import nailPolish from "./productPics/nailPolish.JPG"
import plant from "./productPics/plant.JPG"
import shorts from "./productPics/shorts.JPG"
import stationary from "./productPics/stationary.JPG"
import syrup from "./productPics/syrup.JPG"
import typewriter from "./productPics/typewriter.JPG"
import vase from "./productPics/vase.JPG"

const Products = [
  {
    id: 1,
    image: card,
    name: "Lorem",
    description: "Necessitatibus perferendis voluptas error voluptate",
    price: 17.5,
    brand: "Lee Pucker",
    shipping: "ipsum dolor sit amet consectetur adipisicing",
    rating: 3,
    type: "electronics",
    quantity: 1,
    subTotal: 0,
  },
  {
    id: 2,
    image: cat,
    name: "Lorem ipsumt",
    description: "Necessitatibus perferendis voluptas error voluptate",
    price: 20.5,
    brand: "Lee Pucker",
    shipping: "ipsum dolor sit amet consectetur adipisicing",
    rating: 3,
    type: "beauty",
    quantity: 1,
    subTotal: 0,
  },
  {
    id: 3,
    image: jugs,
    name: "Lorem ipsumt",
    description: "Necessitatibus perferendis voluptas error voluptate",
    price: 14.5,
    brand: "Libuner",
    shipping: "ipsum dolor sit amet consectetur adipisicing",
    rating: 2,
    type: "electronics",
    quantity: 1,
    subTotal: 0,
  },
  {
    id: 4,
    image: makeupBrush,
    name: "Lorem ipsumt",
    description: "Necessitatibus perferendis voluptas error voluptate",
    price: 17.5,
    brand: "Lebkmer",
    shipping: "ipsum dolor sit amet consectetur adipisicing",
    rating: 2,
    type: "beauty",
    quantity: 1,
    subTotal: 0,
  },
  {
    id: 5,
    image: nailPolish,
    name: "Lorem ipsumt",
    description: "Necessitatibus perferendis voluptas error voluptate",
    price: 20.5,
    brand: "balencisgr",
    shipping: "ipsum dolor sit amet consectetur adipisicing",
    rating: 3,
    type: "electronics",
    quantity: 1,
    subTotal: 0,
  },
  {
    id: 6,
    image: plant,
    name: "Lorem ipsumt",
    description: "Necessitatibus perferendis voluptas error voluptate",
    price: 12.5,
    brand: "Lee Pucker",
    shipping: "ipsum dolor sit amet consectetur adipisicing",
    rating: 1,
    type: "beauty",
    quantity: 1,
    subTotal: 0,
  },
  {
    id: 7,
    image: shorts,
    name: "Lorem ipsumt",
    description: "Necessitatibus perferendis voluptas error voluptate",
    price: 10.5,
    brand: "Lehtor",
    shipping: "ipsum dolor sit amet consectetur adipisicing",
    rating: 3,
    type: "electronics",
    quantity: 1,
    subTotal: 0,
  },
  {
    id: 8,
    image: stationary,
    name: "Lorem ipsumt",
    description: "Necessitatibus perferendis voluptas error voluptate",
    price: 8.5,
    brand: "Lee Pucker",
    shipping: "ipsum dolor sit amet consectetur adipisicing",
    rating: 3,
    type: "electronics",
    quantity: 1,
    subTotal: 0,
  },
  {
    id: 9,
    image: syrup,
    name: "Lorem ipsumt",
    description: "Necessitatibus perferendis voluptas error voluptate",
    price: 5.5,
    brand: "honarble",
    shipping: "ipsum dolor sit amet consectetur adipisicing",
    rating: 1,
    type: "beauty",
    quantity: 1,
    subTotal: 0,
  },
  {
    id: 10,
    image: typewriter,
    name: "Lorem ipsumt",
    description: "Necessitatibus perferendis voluptas error voluptate",
    price: 17.5,
    brand: "tejhder",
    shipping: "ipsum dolor sit amet consectetur adipisicing",
    rating: 2,
    type: "beauty",
    quantity: 1,
    subTotal: 0,
  },
  {
    id: 11,
    image: vase,
    name: "Lorem ipsumt",
    description: "Necessitatibus perferendis voluptas error voluptate",
    price: 10.5,
    brand: "tenimakani",
    shipping: "ipsum dolor sit amet consectetur adipisicing",
    rating: 3,
    type: "electronics",
    quantity: 1,
    subTotal: 0,
  },
  {
    id: 12,
    image: card,
    name: "Lorem ipsumt",
    description: "Necessitatibus perferendis voluptas error voluptate",
    price: 10.5,
    brand: "star Boy",
    shipping: "ipsum dolor sit amet consectetur adipisicing",
    rating: 2,
    type: "electronics",
    quantity: 1,
    subTotal: 0,
  },
];
export default Products
